before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
archives:
- format: binary
dockers:
- dockerfile: Dockerfile
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
  image_templates:
  - "us-central1-docker.pkg.dev/totvs-ai-control-plane/totvs-ai-images/gcp-oci-proxy:latest"
  - "us-central1-docker.pkg.dev/totvs-ai-control-plane/totvs-ai-images/gcp-oci-proxy:{{ .Tag }}"